package:
   name: spq
   version: "1.0.0"

source:
   git_rev: v1.0.0
   git_url: https://github.com/gwoptics/SpacePyQuest

requirements:
   host:
    - python
    - bokeh

   run:
   - python

test:
   imports:
   - spq

about:
   home: https://github.com/gwoptics/SpacePyQuest
   licence: GNU General Public License 3
   license_file: gpl-3.0.md
